import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    // Fixed at 3000 so it matches the ?table= example URLs in the README
    // and the sample QR codes generated by scripts/generate-qr.mjs.
    port: 3000,
  },
})
